apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  initContainers:
    - name: artifacts-fetcher
      image: busybox
      command: ['wget', 'https://oceanus/helloworld.jar', '-O', '/flink-artifact/helloworld.jar']
      volumeMounts:
        - mountPath: /flink-artifact
          name: flink-artifact
  containers:
    - name: flink-job-manager
      volumeMounts:
        - mountPath: /opt/flink/volumes/hostpath
          name: flink-volume-hostpath
        - mountPath: /opt/flink/artifacts
          name: flink-artifact
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoExecute"
      tolerationSeconds: 3600

