apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret-env
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: foo1_username
          valueFrom:
            secretKeyRef:
              key: username
              name: mysecret
        - name: foo1_password
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret
        - name: foo2_username
          valueFrom:
            secretKeyRef:
              key: username
              name: mysecret2
        - name: foo2_password
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret2
