apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret-file
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      volumeMounts:
        - mountPath: "/opt/flink/secrets/foo"
          name: foo
          readOnly: true
        - mountPath: "/opt/flink/secrets/foo2"
          name: foo2
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret
    - name: foo2
      secret:
        secretName: mysecret2
